export enum LoginStatus {
    NOT_LOGGED_IN = "NOT_LOGGED_IN",
    LOGGING_IN = "LOGGING_IN",
    LOAD_USER_DETAILS = "LOAD_USER_DETAILS",
    LOADING_USER_DETAILS = "LOADING_USER_DETAILS",
    LOGGED_IN = "LOGGED_IN"
}
