name: Build - Clash Bot WebApp

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
  pull_request:
    branches: [ master ]

jobs:
  check-applications:
    runs-on: ubuntu-latest

    outputs:
      deploy-ui: ${{ steps.check-apps.outputs.uiUpdate }}
      deploy-service: ${{ steps.check-apps.outputs.serviceUpdate }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run shell to check which App to deploy
        id: check-apps
        run: |
          chmod 755 ./check_diff_between_master.sh
          ./check_diff_between_master.sh

      - name: Check Output for Service
        run: echo ${{ steps.check-apps.outputs.serviceUpdate }}

      - name: Check Output for UI
        run: echo ${{ steps.check-apps.outputs.uiUpdate }}

  build-service:
    needs: check-applications
    if: ${{ needs.check-applications.outputs.deploy-service == 'true'}}
    runs-on: ubuntu-latest

    steps:
      - name: Build In Progress Discord Webhook
        uses: Poss111/discord-hook-action@v1.6.8
        with:
          discord-hook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: 'Clash Bot Web App - Service Build - Notification'
          message: 'Build in progress...'
          message-color: '16750902'

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Deploy Service
        run: |
          echo "Running Service!"
          ls -lha

      - name: Archive service artifact
        uses: actions/upload-artifact@v2
        with:
          name: service
          if-no-files-found: error
          path: ClashBot-Service

      - name: Test Failed Discord Webhook
        uses: Poss111/discord-hook-action@v1.6.8
        if: ${{ failure() }}
        with:
          discord-hook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: 'Clash Bot Web App - Service Build - Notification'
          message: 'Service Build Failed!'
          message-color: '16711680'

  test-ui:
    needs: check-applications
    if: ${{ needs.check-applications.outputs.deploy-ui == 'true'}}
    runs-on: ubuntu-latest

    steps:
      - name: Testing In Progress Discord Webhook
        uses: Poss111/discord-hook-action@v1.6.8
        with:
          discord-hook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: 'Clash Bot Web App - UI Test - Notification'
          message: 'Test in progress...'
          message-color: '16750902'

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install depedencies
        working-directory: ./ClashBot-UI
        run: npm i

      - name: Run Tests
        working-directory: ./ClashBot-UI
        run: npm run-script test

      - name: Test Failed Discord Webhook
        uses: Poss111/discord-hook-action@v1.6.8
        if: ${{ failure() }}
        with:
          discord-hook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: 'Clash Bot Web App - UI Integration Test - Notification'
          message: 'UI Test Failed!'
          message-color: '16711680'

  integration-ui:
    needs:
      - test-ui
      - lint-ui
    if: ${{ needs.check-applications.outputs.deploy-ui == 'true'}}
    runs-on: ubuntu-latest

    steps:
      - name: Testing In Progress Discord Webhook
        uses: Poss111/discord-hook-action@v1.6.8
        with:
          discord-hook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: 'Clash Bot Web App - UI Integration Test - Notification'
          message: 'Integration Test in progress...'
          message-color: '16750902'

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: ./ClashBot-UI
        run: npm i

      - name: Run Integration Tests
        working-directory: ./ClashBot-UI
        run: npm run-script cy

      - name: Integration Test Failed Discord Webhook
        uses: Poss111/discord-hook-action@v1.6.8
        if: ${{ failure() }}
        with:
          discord-hook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: 'Clash Bot Web App - UI Integration Test - Notification'
          message: 'UI Integration Test Failed!'
          message-color: '16711680'

  lint-ui:
    needs: check-applications
    if: ${{ needs.check-applications.outputs.deploy-ui == 'true'}}
    runs-on: ubuntu-latest

    steps:
      - name: Linting In Progress Discord Webhook
        uses: Poss111/discord-hook-action@v1.6.8
        with:
          discord-hook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: 'Clash Bot Web App - UI Linting - Notification'
          message: 'Linting in progress...'
          message-color: '16750902'

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: ./ClashBot-UI
        run: npm i

      - name: Run Linting
        working-directory: ./ClashBot-UI
        run: npm run-script lint

      - name: Linting Failed Discord Webhook
        uses: Poss111/discord-hook-action@v1.6.8
        if: ${{ failure() }}
        with:
          discord-hook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: 'Clash Bot Web App - UI Linting - Notification'
          message: 'Linting Failed!'
          message-color: '16711680'

  concluded-testing:
    needs:
      - integration-ui
      - build-service
      - lint-ui
      - test-ui
    if: ${{ always() }}
    runs-on: ubuntu-latest

    steps:
      - name: Check
        run: echo "${{ needs.build-service.result }} ${{ needs.integration-ui.result }} ${{ needs.lint-ui.result }} ${{ needs.test-ui.result }}"

      - name: Testing completed Discord Webhook
        uses: Poss111/discord-hook-action@v1.6.8
        if: ${{ needs.build-service.result == 'failure' || needs.integration-ui.result == 'failure' || needs.lint-ui.result == 'failure' || needs.test-ui.result == 'failure'}}
        with:
          discord-hook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "Clash Bot Web App - Testing Finished - Notification "
          message: 'PR build completed. There is an issue with one or more of the builds. Please check the job. **Build Service**: ${{ needs.build-service.result }} \\n **Linting**: ${{ needs.lint-ui.result }} \\n **UI Tests**: ${{ needs.test-ui.result }} \\n **Integration UI**: ${{ needs.integration-ui.result }}'
          message-color: '16711680'

      - name: Testing completed Discord Webhook
        uses: Poss111/discord-hook-action@v1.6.8
        if: ${{ needs.build-service.result != 'failure' && needs.integration-ui.result != 'failure' && needs.lint-ui.result != 'failure' && needs.test-ui.result != 'failure'}}
        with:
          discord-hook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "Clash Bot Web App - PR check finished - Notification"
          message: 'PR build completed. You are good to merge!!'
          message-color: '65345'
