name: Deployment - Clash Bot WebApp

on:
  push:
    tags:
      - 'v*'

jobs:
  check-applications:
    runs-on: ubuntu-latest

    outputs:
      deploy-ui: ${{ steps.check-apps.outputs.uiUpdate }}
      deploy-service: ${{ steps.check-apps.outputs.serviceUpdate }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run shell to check which App to deploy
        id: check-apps
        run: |
          chmod 755 ./check_diff_between_tags.sh
          ./check_diff_between_tags.sh

      - name: Check Output for Service
        run: echo ${{ steps.check-apps.outputs.serviceUpdate }}

      - name: Check Output for UI
        run: echo ${{ steps.check-apps.outputs.uiUpdate }}

  deploy-service:
    if: ${{ needs.check-applications.outputs.serviceUpdate }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Service
        run: |
          echo "Running Service!"
          ls -lha

  deploy-ui:
    if: ${{ needs.check-applications.outputs.uiUpdate }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy UI
        run: |
          echo "Running UI!"
          ls -lha
