name: Responsive Testing

on:
  push:
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'

jobs:
  mobile:
    name: "Mobile Responsive Testing"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Dependencies for E2E Suite
        working-directory: ./ClashBot-E2E
        run: npm i

      - name: Start App container
        working-directory: ./ClashBot-Service-OpenAPI
        run: docker-compose up -d

      - name: Run Integration Tests
        id: integration
        working-directory: ./ClashBot-E2E
        timeout-minutes: 5
        env:
          APP_AUTH0_CLIENTID: ${{ secrets.DISCORD_SECRET_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.DISCORD_SECRET_KEY }}
          AUTH0_GRANT_TYPE: ${{ secrets.DISCORD_GRANT_TYPE }}
          APP_AUTH0_SCOPE: ${{ secrets.DISCORD_SCOPE }}
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_KEY }}
          RESOLUTION: "iphone-8"
        continue-on-error: true
        run: npm run-script cy-responsive

      - name: Output failure logs
        if: steps.integration.outcome == 'failure'
        working-directory: ./ClashBot-Service-OpenAPI
        run: docker compose logs > failure-logs.log

  desktop:
    name: "Desktop Responsive Testing"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Dependencies for E2E Suite
        working-directory: ./ClashBot-E2E
        run: npm i

      - name: Start App container
        working-directory: ./ClashBot-Service-OpenAPI
        run: docker-compose up -d

      - name: Run Integration Tests
        id: integration
        working-directory: ./ClashBot-E2E
        timeout-minutes: 5
        env:
          APP_AUTH0_CLIENTID: ${{ secrets.DISCORD_SECRET_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.DISCORD_SECRET_KEY }}
          AUTH0_GRANT_TYPE: ${{ secrets.DISCORD_GRANT_TYPE }}
          APP_AUTH0_SCOPE: ${{ secrets.DISCORD_SCOPE }}
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_KEY }}
          RESOLUTION: "macbook-16"
        continue-on-error: true
        run: npm run-script cy-responsive

      - name: Output failure logs
        if: steps.integration.outcome == 'failure'
        working-directory: ./ClashBot-Service-OpenAPI
        run: docker compose logs > failure-logs.log


