name: Test out dependent jobs

jobs:
  check-applications:
    runs-on: ubuntu-latest

    outputs:
      deploy-ui: ${{ steps.check-apps.outputs.uiUpdate }}
      deploy-service: ${{ steps.check-apps.outputs.serviceUpdate }}

    steps:
      - name: Sample Run
        run: echo 'Hi'

  build-service:
    needs: check-applications
    if: ${{ needs.check-applications.outputs.deploy-service == 'true'}}
    runs-on: ubuntu-latest

    steps:
      - name: Sample Run
        run: echo 'Hi'

  build-ui:
    needs: check-applications
    if: ${{ needs.check-applications.outputs.deploy-ui == 'true'}}
    runs-on: ubuntu-latest

    steps:
      - name: Sample Run
        run: echo 'Hi'

  deploy-ui:
    needs: |
      build-ui
      build-service
    runs-on: ubuntu-latest

    steps:
      - name: Sample Run
        run: echo 'Hi'
