name: Build

on:
  push:
    branches: [ master ]
    paths:
      - 'ClashBot-UI/**'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: FranzDiebold/github-env-vars-action@v2.1.0

      - name: Check
        run: echo build $GITHUB_RUN_NUMBER

      - uses: actions/checkout@v2

      - name: Quick echo
        run: echo 'UI has changed'
